### ISSUE TITLE
Can you please put some comments?

### ISSUE THREAD

**Issue by SaraDN** [durzoflint/N-Queens#1]
Can you please explain step by step what your algorithm is doing? I've been struggling to understand backtracking via google, and your code seems to me to be the most approaching. Maybe you can put some comments behind each line of code and tell, step by step, what you code does? That would really help me! -Please

**Comment by durzoflint** [comment]
Sure, I will. But I have my exams right now. Could you ping me again tomorrow? I'll add it then.

**Comment by SaraDN** [comment]
Yes! Thank you so much <3

**Comment by durzoflint** [comment]
Added the comments. You can now better understand the code. Let me know if you need more help. Also, there are more examples of recursion and backtracking in my GitHub profile. Uploaded around the same time. You can look at them for a better understanding.

**Comment by durzoflint** [comment]
@SaraDN If you don't mind, could you tell me how you found this repository?

**Comment by SaraDN** [comment]
I was just searching Backtracking Queens Problem Java and after checking a couple of other Repositories, I've found yours.

**Comment by SaraDN** [comment]
Thank you so much for adding comments!! If you ever have time, can you please make some templates of how to use backtracking?

**Comment by durzoflint** [comment]
@SaraDN , you are most welcome. I am always ready to help a fellow programmer or a developer.
About the templates, I believe they are really not necessary. Backtracking is not a very big concept or anything. It's just a way of writing code which doesn't go in a `stackoverflow exception` and implements your logic.

Let me be a little clear, see line _**57**_. I have called the same function `generate()`, after placing the queen at line _**50**_. This is normal recursion. After doing that, I removed the queen in line _**61**_.

The removing of the queen right after recursion is the key. This allows more combinations to the program. The loop moves forward and places the queen on the next favorable block.

So logically, the queen is placed, then recursion occurs. The recursion places the next queen somewhere else(as per the conditions). _**If**_ the queens later do not fit, or the conditions are not followed, or, _**when**_ the recursion is finally over(the function call will get over and the program will return the previous recursive call). You need to move this queen(done on line _**61**_).

I know this seems a little bit confusing, but read this a few times and read the code as this comment explains, I am sure you will understand.

**Comment by SaraDN** [comment]
Thank you so much for being so supportive! If I'll have new questions, I'll ask them to you. I'm so happy I've finally found someone that actually is patient with beginners! :) Have a great day, and thank you again!

**Comment by durzoflint** [comment]
You are most welcome @SaraDN . Happy Coding. :-)
